CLASS zbp_i_bank_vj DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_bank_vj.
  PUBLIC SECTION.
    CLASS-DATA:wl_test TYPE string.
  PROTECTED SECTION.

  PRIVATE SECTION.
ENDCLASS.



CLASS zbp_i_bank_vj IMPLEMENTATION.
ENDCLASS.
